[package]
name = "snowflake-rs"
version = "0.1.0"
authors = ["Will Gulian <will@willgulian.com>"]

[dependencies]
byteorder = "1.1.0"
bytes = "0.4.5"
time = "0.1.38"
futures = "0.1.15"
tokio-core = "0.1.9"
tokio-io = "0.1.3"
tokio-proto = "0.1.1"
tokio-service = "0.1.0"
